// packages/enrollment-platform/src/components/layout/Header.vue
<script setup lang="ts">
import logo from '../../assets/gcu-womd.png'
import avatar from "../../assets/vue.svg"
</script>
<template>
  <div class="h-full flex justify-between items-center">
    <div class="flex gap-x-4 items-center">
      <img :src="logo" class="w-14" />
      <h1>招新系统后台</h1>
    </div>
    <div class="flex gap-x-2 items-center">
      <el-avatar :src="avatar" />
      <el-dropdown>
        <div class="flex gap-x-2 cursor-pointer focus-visible:outline-none">
          <el-text size="large">Jammie Griffin</el-text>
          <div class="i-ep:arrow-down"></div>
        </div>
        <template #dropdown>
          <el-dropdown-item>站点导航</el-dropdown-item>
        </template>
      </el-dropdown>
    </div>
  </div>
</template>
<style scoped lang="scss"></style>

// packages/CMS/src/layout/Header.tsx
import { Avatar } from 'antd'
import reactIcon from '../assets/react.svg'
import { useNavigate } from 'react-router-dom'
const Header = () => {
  const nav = useNavigate()
  return (
    <>
      <div className="w-screen px-8 py-4 bg-white fixed top-0 left-0 right-0 z-99">
        <div className="flex w-full justify-between items-center">
          <h2>网站运维部博客系统</h2>
          <div className="flex items-center">
            <ul className="list-none mr-8 flex flex-row gap-x-4">
              <li className="cursor-pointer">广场</li>
              <li
                className="cursor-pointer"
                onClick={() => {
                  nav('/profile/123')
                }}
              >
                我的主页
              </li>
            </ul>
            <div>
              <Avatar src={reactIcon} />
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
export default Header
